### ISSUE TITLE
Shift+clicking item(s) from hotbar to full inventory with backpack on deletes said item(s)

### ISSUE THREAD

**Issue by Andrew-144** [kohanis/raft-comfortable-inventory#1]
I've noticed when I try to shift click an item or stack of items from my hotbar to my full inventory with a normal backpack on, it straight up deletes the item. I've tested it to make sure it was this mod and it was. I am also unable to take off the backpack after it happens.

**Comment by kohanis** [comment]
Fixed in 1.0.3

Use `csrun var inv = RAPI.GetLocalPlayer().Inventory; inv.allSlots.Where(x => !x.active && !x.IsEmpty).Do(x => inv.DropItem(x));` in console to fix current backpack
