### ISSUE TITLE
Cooked food not sorting to hotbar

### ISSUE THREAD

**Issue by garagesailor** [kohanis/raft-comfortable-inventory#2]
Cooked food ends up in inventory not hotbar. Tried toggling the setting off and then back on but the issue still persists. Tools and buildables move correctly.

Version 1.2.0 of the mod
ModLoader v6.4.1
Raft  v1.09

**Comment by kohanis** [comment]
Which one? Can't reproduce with any cooked food

**Comment by garagesailor** [comment]
It's cooked fish that ends up in the inventory. I was still early game so I hadn't reached the cooking pot stage yet. The cooked food from the pot does properly sort. 

Also would it be possible to have clay bowls go to your hotbar instead of your inventory as well.

**Comment by kohanis** [comment]
Fixed and added with 1.2.3
